DROP DATABASE IF EXISTS book_store;
CREATE DATABASE book DEFAULT CHARACTER SET UTF8;
USE book;

DROP TABLE IF EXISTS `user`;
drop table if EXISTS `admin`;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS orderitem;
DROP TABLE IF EXISTS notice;
DROP TABLE IF EXISTS category;

DROP DATABASE IF EXISTS book_store;
CREATE DATABASE book_store DEFAULT CHARACTER SET UTF8;
USE book_store;

DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS orderitem;
DROP TABLE IF EXISTS notice;
DROP TABLE IF EXISTS category;

create table admin(
  id int PRIMARY KEY AUTO_INCREMENT,
  username varchar(20) UNIQUE ,
  passwd VARCHAR(50) not null
)ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT = 1;


create table category(
  id INT primary key AUTO_INCREMENT,
  name varchar(100) not null unique,
  description varchar(255)
)ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT = 1;

CREATE TABLE user
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(20) NOT NULL,
  password VARCHAR(20) NOT NULL,
  gender tinyint,
  email VARCHAR(50),
  mobilephone VARCHAR(20),
  address varchar(100),
  state TINYINT DEFAULT 0,
  registTime TIMESTAMP NOT NULL DEFAULT current_timestamp()
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT = 1;

CREATE TABLE book
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(40),
  price DOUBLE DEFAULT 0.0,
  category_id VARCHAR(40),
  num INT,
  author varchar(20),
  image_Url VARCHAR(100),
  description VARCHAR(255),
  PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT = 1;

CREATE TABLE orders
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  money DOUBLE,
  receiveAddress VARCHAR(255),
  receiveName VARCHAR(20),
  reveicePhone VARCHAR(20),
  paystate INT,
  orderTime TIMESTAMP DEFAULT '2016-01-01 00:00:00',
  user_id INT
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT = 1;

CREATE TABLE orderitem
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  order_id VARCHAR(100) NOT NULL,
  product_id VARCHAR(100),
  buynum INT
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT = 1;

CREATE TABLE notice
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(10),
  details VARCHAR(255),
  time VARCHAR(18)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT = 1;